# Create docker-compose.yml in project root
version: '3.8'
services:
  mongodb:
    image: mongo:8.0
    container_name: artisan-ai-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: artisanai
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: